/*
    The layout for a page is constructed Here, Intialize our theme provider
    as the parent component, this allows the theme to be passed to all of its children
    dark/light.
    The header is initalized here. This is how it will be intialized on every page,


    Written By Owen Lennox
 */



import type { Metadata } from "next";
import "./globals.css";
import Header from '@/components/Header'
import ThemeProvider from './context/ThemeContext'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>
      <ThemeProvider> {/* allows is Dark mode to be used in every component*/}
          <Header/>  {/*  static header*/}
          {children}
      </ThemeProvider>
      </body>
      </html>
  );
}
